### ISSUE TITLE
Add example import for ES6 to README

### ISSUE THREAD

**Issue by eljenso** [MrHuds0n/nrdb#1]
Example import:
```
import * as nrdb from 'nrdb';
```

From there, everything works like in your already present example.

**Comment by zanlib0** [comment]
ES6 imports are not supported in the latest version of Node (without the usage of a transpiler such as Babel) which is the reason for not including this in the readme. The npm module published to the registry is the already transpiled code from ESNext to ES5 which is why you see the import statements in the code.

Additionally, I would expect someone who insists on using bleeding-edge features (like ES6) would know how to use the import statements.
